### ISSUE TITLE
Exception thrown after 'timeout'

### ISSUE THREAD

**Issue by deepsorrow** [SirRade/JNF_NEAT#100]
Whenever I try to run one of the Tests and when `std::chrono::seconds timeout(somevalue)` runs out, this is what pops up:
![313](https://cloud.githubusercontent.com/assets/21280973/21702403/bbf157a2-d3dd-11e6-9b0d-2224b3b019b4.png)
I use VS 2017 RC, my OS is Windows 10 x64
Could you please help me?

UPD:
I've just figured it out that everything works fine in 'Release' mode.

**Comment by janhohenheim** [comment]
This our not-so-clean solution for letting tests fail if they time out.  See #63 and #90.

The time values were found empirically by testing the release mode, that's why you are getting these results.  
To override the time settings, change the value in line `std::chrono::seconds timeout(100);` to how many seconds you need.  

Btw, if you're wondering why a simple XOR test takes so long, it's because this specific test gets extensively logged in the background. I advise you to delete your `json_dumps` folder once you've run the test multiple times ;)
